In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
       'the glass of juice',
       'the cup of tea',
       'I am a good boy',
       'I am a good developer',
       'understand the meaning of words',
       'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size =  10000

**One Hot Representation**

In [5]:
onehot_repr = [one_hot(words, voc_size)for words in sent]
onehot_repr

[[6992, 7328, 519, 513],
 [6992, 7328, 519, 8657],
 [6992, 3764, 519, 9283],
 [1664, 7584, 1018, 4078, 1977],
 [1664, 7584, 1018, 4078, 7019],
 [1375, 6992, 2542, 519, 6844],
 [2072, 4703, 1096, 4078]]

**Word Embedding Representation**

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding = 'pre',maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 6992 7328  519  513]
 [   0    0    0    0 6992 7328  519 8657]
 [   0    0    0    0 6992 3764  519 9283]
 [   0    0    0 1664 7584 1018 4078 1977]
 [   0    0    0 1664 7584 1018 4078 7019]
 [   0    0    0 1375 6992 2542  519 6844]
 [   0    0    0    0 2072 4703 1096 4078]]


In [12]:
dim = 10 # features size

In [13]:
model =Sequential()
model.add(Embedding(voc_size,dim,input_length = sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step
[[[-0.02290311  0.01563147  0.03879625  0.00668789 -0.02707598
    0.02964072 -0.0008424  -0.00549136  0.01847643 -0.02659019]
  [-0.02290311  0.01563147  0.03879625  0.00668789 -0.02707598
    0.02964072 -0.0008424  -0.00549136  0.01847643 -0.02659019]
  [-0.02290311  0.01563147  0.03879625  0.00668789 -0.02707598
    0.02964072 -0.0008424  -0.00549136  0.01847643 -0.02659019]
  [-0.02290311  0.01563147  0.03879625  0.00668789 -0.02707598
    0.02964072 -0.0008424  -0.00549136  0.01847643 -0.02659019]
  [-0.02853906 -0.0020263  -0.01212088  0.02621769 -0.02655791
    0.04287386  0.0028551   0.03269191  0.02535545 -0.04163054]
  [ 0.0455986   0.00049093  0.0339505   0.02603302 -0.04251487
    0.02530546 -0.04873786 -0.00756565 -0.04026698  0.0360874 ]
  [-0.03434919 -0.00852673 -0.01521478 -0.00457542 -0.00791347
   -0.03494366  0.02699311 -0.00463108 -0.01956074  0.04075417]
  [ 0.01026575  0.03614471  0.03321507  0.03276579 -0.03162067
   -0.005

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 6992, 7328,  519,  513], dtype=int32)

In [17]:
print(model.predict(embedded_docs)[0]) 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[-0.02290311  0.01563147  0.03879625  0.00668789 -0.02707598  0.02964072
  -0.0008424  -0.00549136  0.01847643 -0.02659019]
 [-0.02290311  0.01563147  0.03879625  0.00668789 -0.02707598  0.02964072
  -0.0008424  -0.00549136  0.01847643 -0.02659019]
 [-0.02290311  0.01563147  0.03879625  0.00668789 -0.02707598  0.02964072
  -0.0008424  -0.00549136  0.01847643 -0.02659019]
 [-0.02290311  0.01563147  0.03879625  0.00668789 -0.02707598  0.02964072
  -0.0008424  -0.00549136  0.01847643 -0.02659019]
 [-0.02853906 -0.0020263  -0.01212088  0.02621769 -0.02655791  0.04287386
   0.0028551   0.03269191  0.02535545 -0.04163054]
 [ 0.0455986   0.00049093  0.0339505   0.02603302 -0.04251487  0.02530546
  -0.04873786 -0.00756565 -0.04026698  0.0360874 ]
 [-0.03434919 -0.00852673 -0.01521478 -0.00457542 -0.00791347 -0.03494366
   0.02699311 -0.00463108 -0.01956074  0.04075417]
 [ 0.01026575  0.03614471  0.03321507  0.03276579 -0.03162067 -0.00593645
  -0.04561908